### ISSUE TITLE
the  Withdrawals not work

### ISSUE THREAD

**Issue by romeox6x66** [phpfaucet/faucet#1]
the 
Withdrawals
 not work

**Comment by phpfaucet** [comment]
to pay withdrawals, browse cron_withdrawal.php manually or set a cronjob to process withdrawals in a specified time.

**Comment by romeox6x66** [comment]
how to browse i dont know

**Comment by phpfaucet** [comment]
open the link in firefox or chrome. http://yourfaucet.com/cron_withdrawal.php

**Comment by mahuaroy** [comment]
After open the link cron_withdrawal.php showing Blank Screen.

**Comment by mahuaroy** [comment]
Any php verson
